import fs from 'fs';
import path from 'path';

import { notFound } from 'next/navigation';
import { unified } from 'unified';
import { visit } from 'unist-util-visit';

import { CALENDAR_SVG, PAGE_SVG } from "@/utils/elements";

import remarkParse from 'remark-parse';
import remarkMath from 'remark-math';
import remarkRehype from 'remark-rehype';
import rehypeKatex from 'rehype-katex';
import rehypePrettyCode from 'rehype-pretty-code';
import rehypeStringify from 'rehype-stringify';
import remarkGfm from 'remark-gfm';
import rehypeRaw from 'rehype-raw';
import 'katex/dist/katex.min.css';

import Section from "../common/Section";
import BlogPosts from "../common/BlogPosts";

interface BlogSlugProps {
    blog: string;
}


export async function Blog() {
    return (
        <Section index="01" label="blog" heading="my thoughts">
            <BlogPosts />
        </Section>
    )
}

// this rehypeCopyButton function was generated by AI.
function rehypeCopyButton() {
    return (tree: any) => {
        visit(tree, 'element', (node) => {
            if (node.tagName === 'pre') {
                node.properties = node.properties || {};
                node.properties.style = 'position: relative;';
                node.children.push({
                    type: 'element',
                    tagName: 'button',
                    properties: {
                        style: 'position:absolute;top:8px;right:8px;background:black;border:1px solid rgba(180,83,9,0.4);padding:6px;cursor:pointer;color:rgba(180,83,9,0.6);border-radius:4px;',
                        title: 'Copy code',
                        onclick: `
                            const btn = this;
                            const code = this.parentElement.querySelector('code');
                            navigator.clipboard.writeText(code.innerText);
                            btn.innerHTML = '<svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M2 6 L5 9 L10 3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';
                            setTimeout(() => {
                                btn.innerHTML = '<svg width="12" height="12" viewBox="0 0 12 12" fill="none"><rect x="1" y="3" width="7" height="8" stroke="currentColor" stroke-width="1.2"/><path d=\\"M3 3 L3 2 L10 2 L10 9 L9 9\\" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"/></svg>';
                            }, 2000);
                        `
                    },
                    children: [{
                        type: 'raw',
                        value: '<svg width="12" height="12" viewBox="0 0 12 12" fill="none"><rect x="1" y="3" width="7" height="8" stroke="currentColor" stroke-width="1.2"/><path d="M3 3 L3 2 L10 2 L10 9 L9 9" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"/></svg>'
                    }]
                });
            }
        });
    };
}


export async function BlogSlug({ blog }: BlogSlugProps) {
    const filePath = path.join(process.cwd(), 'public', 'blog_posts', `${blog}.md`);

    if (!fs.existsSync(filePath)) notFound();

    const content = fs.readFileSync(filePath, 'utf-8');
    const [titleLine, description] = content.split('\n');
    const title = titleLine.replace(/^#+ /, '');
    const stats = fs.statSync(filePath);
    const readTime = Math.ceil(content.split(/\s+/).length / 200);
    const fmt = (d: Date) => new Intl.DateTimeFormat('en-US', { month: 'long', day: 'numeric', year: 'numeric' }).format(d);

    const html = await unified()
        .use(remarkParse)
        .use(remarkMath)
        .use(remarkGfm)
        .use(remarkRehype, { allowDangerousHtml: true })
        .use(rehypeRaw)
        .use(rehypeKatex)
        .use(rehypePrettyCode, {
            theme: 'one-dark-pro',
        })
        .use(rehypeCopyButton)
        .use(rehypeStringify, { allowDangerousHtml: true })
        .process(content);

    return (
        <div className="max-w-3xl mx-auto p-8 font-mono">
            <div className="border border-amber-600/20 bg-amber-600/5 p-4 mb-8 flex flex-col gap-2">
                <p className="text-amber-600/40 text-[10px] uppercase tracking-widest">// blog post</p>
                <h1 className="text-amber-400 uppercase tracking-widest text-lg">{title}</h1>
                <p className="text-amber-600/50 text-xs">{description}</p>
                <div className="flex gap-6 mt-2 text-[10px] uppercase tracking-widest text-amber-600/40">
                    <span className="flex items-center gap-1">{CALENDAR_SVG} created {fmt(stats.birthtime)}</span>
                    <span className="flex items-center gap-1">{CALENDAR_SVG} updated {fmt(stats.mtime)}</span>
                    <span className="flex items-center gap-1">{PAGE_SVG} {readTime} min read</span>
                </div>
            </div>
            <div className="prose prose-invert prose-amber max-w-none font-mono transition-all duration-200
                prose-headings:text-amber-400 prose-headings:uppercase prose-headings:tracking-widest
                prose-p:text-amber-600/70
                prose-a:text-amber-500 prose-a:hover:scale-110 prose-a:inline-block prose-a:underline prose-a:underline-offset-4
                prose-strong:text-amber-400
                prose-pre:bg-black prose-pre:border prose-pre:border-amber-600/20 prose-pre:rounded-sm
                prose-code:text-amber-400 prose-code:bg-amber-600/10 prose-code:border prose-code:border-amber-600/20 prose-code:rounded-none prose-code:px-1 prose-code:before:content-none prose-code:after:content-none
                [&_pre_code]:bg-transparent [&_pre_code]:border-0 [&_pre_code]:p-0 [&_pre_code]:text-inherit [&_pre_code]:before:content-none [&_pre_code]:after:content-none
                prose-blockquote:border-l-amber-600/40 prose-blockquote:text-amber-600/50
                prose-li:text-amber-600/70 prose-hr:border-amber-600/20
                [&_.katex]:text-amber-500"
                dangerouslySetInnerHTML={{ __html: String(html) }}
            />
        </div>
    );
}